apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 10
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - image: nicho90/service-b:1.0.2
        name: service-b
        resources:
          limits:
            cpu: "200m"  # 200 milliCPU (0.2 CPU cores)
            memory: "256Mi"  # 256 megabytes
          requests:
            cpu: "100m"  # 100 milliCPU (0.1 CPU cores)
            memory: "128Mi"  # 128 megabytes
        ports:
        - containerPort: 6000
        env:
        - name: SERVICE_A_HOST
          value: "service-a"
        - name: SERVICE_A_PORT
          value: "6000"
        - name: SERVICE_A_API_KEY
          value: "abc"
        - name: SERVICE_B_PORT
          value: "6000"
        restartPolicy: Always
        # Startup probe
        startupProbe:
          httpGet:
            path: /ping
            port: 6000
        initialDelaySeconds: 3
        periodSeconds: 3     
        # Liveness probe
        livenessProbe:
          httpGet:
            path: /health
            port: 6000
          initialDelaySeconds: 3
          periodSeconds: 3
        # Readiness probe
        readinessProbe:
          httpGet:
            path: /ready
            port: 6000
          initialDelaySeconds: 3
          periodSeconds: 3