apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - image: nicho90/service-a:1.0.0
        name: service-a
        ports:
        - containerPort: 6000
        env:
        - name: SERVICE_A_PORT
          value: 6000
        - name: SERVICE_A_API_KEY
          value: abc
        - name: SERVICE_A_API_KEY_NEW
          value: abc
        - name: SERVICE_A_API_KEY_OLD
          value: abc