apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - image: nicho90/service-a:1.0.1
        name: service-a
        resources:
          limits:
            cpu: "200m"  # 200 milliCPU (0.2 CPU cores)
            memory: "256Mi"  # 256 megabytes
          requests:
            cpu: "100m"  # 100 milliCPU (0.1 CPU cores)
            memory: "128Mi"  # 128 megabytes
        ports:
        - containerPort: 6000
        env:
        - name: SERVICE_A_PORT
          value: "6000"
        - name: SERVICE_A_API_KEY
          value: "abc"
        - name: SERVICE_A_API_KEY_NEW
          value: "abc"
        - name: SERVICE_A_API_KEY_OLD
          value: "abc"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        