apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - image: nicho90/service-b:1.0.0
          name: service-b
          ports:
            - containerPort: 6000
          envs:
            - name: SERVICE_A_PORT
              value: 6000
            - name: SERVICE_B_PORT
              value: 6000
            - name: SERVICE_A_API_KEY
              value: abc